### ISSUE TITLE
cannot open SGF file which file name contains CJK characters

### ISSUE THREAD

**Issue by missdeer** [bernds/q5Go#3]
as per the explanation at https://stackoverflow.com/a/4644922, the code below works for me:

```cpp
void ClientWindow::slotFileOpen(bool)
{
	QString fileName(QFileDialog::getOpenFileName(this, tr ("Open SGF file"), setting->readEntry("LAST_DIR"),
						      tr("SGF Files (*.sgf *.SGF);;MGT Files (*.mgt);;XML Files (*.xml);;All Files (*)")));
	if (fileName.isEmpty())
		return;

#if defined (Q_OS_WIN)
    QByteArray qba = fileName.toLocal8Bit();
#else
    QByteArray qba = fileName.toUtf8();
#endif
    open_window_from_file (qba.constData ());
}
```

**Comment by bernds** [comment]
This is an area I'm still trying to figure out. q4go used QFile to open SGF files, and that failed on both Linux and Windows. That's why it's now using fstream with the utf8 conversion, and that works on Linux at least. But I do want to test at some point whether QFile in Qt5 behaves better than it did in Qt4.

When you say this works for you - what is your locale on Windows? The documentation says that the conversion is undefined if the string contains characters not representable in the locale, which I would have guessed is true for CJK characters in something like Latin1.

**Comment by missdeer** [comment]
systeminfo.exe prints my system locale is `zh-cn;中文(中国)`

**Comment by bernds** [comment]
I tested it on my Windows machine which presumably uses Latin1, and it did not work - as expected. Instead I changed everything to use QFile instead of C++ standard streams, which now appears to work in Qt5. Please verify that it works on your machine too.

**Comment by bernds** [comment]
Assuming fixed. Reopen if something still needs work.
