### ISSUE TITLE
set quiet value isn't being saved

### ISSUE THREAD

**Issue by nsklaus** [bernds/q5Go#36]
each time i connect on igs, i have to manually set quiet to be false.
i want to see the server message. q5go doesn't seem to save my choice for quiet as it does for other settings, like: looking and open

**Comment by bernds** [comment]
Are looking and open saved server-side? Because q5go doesn't save them, as far as I can tell.
The "server messages" description goes back to qGo and is probably a little misleading. If not in quiet mode, IGS will send updates when players join/leave and games start and end. The problem is, it's not super reliable - it ignores rooms, apparently it doesn't reliably identify black and white for games, etc. So the default is quiet mode for IGS; again going back to qGo (possibly also because updating the lists used to be very expensive on Windows).
I suppose it would be possible to save the setting as a per-server value.

**Comment by nsklaus** [comment]
perhaps, when user clicks one of those buttons like 'quiet' save it as a setting in q5go somewhere, and have it send that value to igs each time user connects ?
in my case for example q5go would always send "set quiet false" to igs at connection time, and this until i decide to click that button again to set quiet to true.

**Comment by bernds** [comment]
I think this is solved now.
